version: "3.9"

services:
  medicalcoder-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_PATH=/app/medical_coder.db
      - WORKSPACE_DIR="agent_workspace"
    volumes:
      - medicalcoder-data:/app
    restart: always

volumes:
  medicalcoder-data:
    driver: local
